### ISSUE TITLE
Migrate to mysqld_safe

### ISSUE THREAD

**Issue by PurpleBooth** [UKHomeOffice/docker-mysql#3]
> mysqld_safe is the recommended way to start a mysqld server on Unix and NetWare. mysqld_safe adds some safety features such as restarting the server when an error occurs and logging runtime information to an error log file.

**Comment by allandegnan** [comment]
I'm not sure this actually adds anything as our containers will just restart in the event of a mysqld crash, but it probably doesn't detract anyhing so I don't really mind.

If we do this set or symlink that log file to stderr.

**Comment by PurpleBooth** [comment]
@vaijab Any opinion on this?

**Comment by PurpleBooth** [comment]
It's worth noting the "official" docker mysql image doesn't do this, and this MySQL runs as the "mysql" user.

**Comment by vaijab** [comment]
Can close this one now?
